<?php
namespace Syjbd\SyRedis\lib;

class RedisList extends RedisBase {

    public function LIndex($index)
    {
        return $this->redis->lIndex($this->key, $index); // TODO: Change the autogenerated stub
    }

    public function lInsert($position, $pivot, $value): int
    {
        return $this->redis->lInsert($this->key, $position, $pivot, $value);
    }

    public function lLen()
    {
        return $this->redis->lLen($this->key);
    }

    public function lPop()
    {
        return $this->redis->lPop($this->key); // TODO: Change the autogenerated stub
    }

    public function lPush($value)
    {
        return $this->redis->lPush($this->key, ...$value); // TODO: Change the autogenerated stub
    }

    public function lPushx($value)
    {
        return $this->redis->lPushx($this->key, $value); // TODO: Change the autogenerated stub
    }

    public function lRange( $start, $end)
    {
        return $this->redis->lRange($this->key, $start, $end); // TODO: Change the autogenerated stub
    }

    public function lRem($value, $count)
    {
        return $this->redis->lRem($this->key, $value, $count); // TODO: Change the autogenerated stub
    }

    public function lSet($index, $value)
    {
        return $this->redis->lSet($this->key, $index, $value); // TODO: Change the autogenerated stub
    }

    public function lTrim($start, $stop)
    {
        return $this->redis->lTrim($this->key, $start, $stop); // TODO: Change the autogenerated stub
    }

    public function rPop()
    {
        return $this->redis->rPop($this->key); // TODO: Change the autogenerated stub
    }

    public function rpoplpush($srcKey, $dstKey)
    {
        return $this->redis->rpoplpush($srcKey, $dstKey); // TODO: Change the autogenerated stub
    }

    public function rPush(...$value)
    {
        return $this->redis->rPush($this->key, ...$value); // TODO: Change the autogenerated stub
    }

    public function rPushx( $value)
    {
        return $this->redis->rPushx($this->key, $value); // TODO: Change the autogenerated stub
    }
}